# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: newworld_development
  username: postgres
  password: Ocean17
  host: localhost

test:
  <<: *default
  database: newworld_test
  username: postgres
  password: Ocean17

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
